version: 0.0
os: windows
files:
  - source: /
    destination: C:\inetpub\wwwroot\YourAppFolder
hooks:
  ApplicationStart:
    - location: scripts/start_api.ps1
      timeout: 300
  ValidateService:
    - location: scripts/validate_service.ps1
      timeout: 300
