version: 0.0
os: windows
files:
  - source: C:\MyCicdApplication\AwsConsolerepo\PipelineTesting
    destination: C:\inetpub\wwwroot\myapi
hooks:
  BeforeInstall:
    - location: scripts/stop_server.ps1
      timeout: 300
      runas: Administrator

  AfterInstall:
    - location: scripts/install_dependencies.ps1
      timeout: 300
      runas: Administrator

  ApplicationStart:
    - location: scripts/start_server.ps1
      timeout: 300
      runas: Administrator
