version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 6.0
  pre_build:
    commands:
      # Restore dependencies
      - cd C:\MyCicdApplication\AwsConsolerepo\PipelineTesting
      - dotnet restore
      
  build:
    commands:
      # Build the project
      - dotnet build --configuration Release
      
  post_build:
    commands:
      # Publish the project
      - dotnet publish --configuration Release --output C:\MyCicdApplication\AwsConsolerepo\PipelineTesting\publish
      
artifacts:
  files:
    - 'C:\MyCicdApplication\AwsConsolerepo\PipelineTesting\publish/**/*'
  discard-paths: yes
